#!/usr/bin/env bash

mc_port=25566
port=${1:-${PORT:-8080}}

if [ -z "$NGROK_API_TOKEN" ]; then
  echo "You must set the NGROK_API_TOKEN config var to create a TCP tunnel!"
  exit 1
fi

# Start the TCP tunnel
ngrok_cmd="bin/ngrok tcp ${mc_port} --authtoken $NGROK_API_TOKEN ${NGROK_OPTS}"
echo "Starting ngrok..."
eval "$ngrok_cmd &"
ngrok_pid=$!

# Do an inline sync first, then start the background job
echo "Starting sync..."
bin/sync
if [ "$READ_ONLY" != "true" ]; then
  eval "while true; do sleep ${AWS_SYNC_INTERVAL:-60}; bin/sync; done &"
  sync_pid=$!
fi

# create server config
echo "server-port=${mc_port}" >> /app/server.properties
for f in whitelist banned-players banned-ips ops; do
  test ! -f $f.json && echo -n "[]" > $f.json
done

mem=$(free -b | awk 'NR==2{print $7}')
if [[ $mem -gt 2147483648 ]]; then
  heap="4g"    # If available memory is greater than 2GB, P-L
elif [[ $mem -gt 1073741824 ]]; then
  heap="2g"    # If available memory is greater than 1GB, P-M
elif [[ $mem -gt 536870912 ]]; then
  heap="768m"    # If available memory is greater than 512MB
else
  heap="384m"  # If available memory is less than 512MB
fi

echo "Starting: minecraft ${mc_port}"
eval "screen -L -h 2048 -dmS minecraft java -Xmx${heap} -Xms${heap} -jar minecraft.jar nogui"
main_pid=$!

# Flush the logfile every second, and ensure that the logfile exists
screen -X "logfile 1" && sleep 1

echo "Tailing log"
eval "tail -f screenlog.0 &"
tail_pid=$!

trap "kill $ngrok_pid $main_pid $sync_pid $tail_pid" SIGTERM
trap "kill -9 $ngrok_pid $main_pid $sync_pid $tail_pid; exit" SIGKILL

eval "ruby -rwebrick -e'WEBrick::HTTPServer.new(:BindAddress => \"0.0.0.0\", :Port => ${port}, :MimeTypes => {\"rhtml\" => \"text/html\"}, :DocumentRoot => Dir.pwd).start'"
